---
# JUNOS command playbook

- name: Running command(s) on Junos device(s)
  hosts: "{{ hosts }}"
  vars_files:
    - creds.yml
  connection: local
  gather_facts: no

  tasks:
    - name: Running...
      junos_command:
        display: "text"
        timeout: "60"
        host: "{{ ansible_host }}"
        username: "{{ login_name }}"
        password: "{{ login_password }}"
        commands:
          - "show evpn instance"
          - "show evpn database"
          - "show configuration groups evpn-multihoming-mx"

      register: device_output

    - name: Show result
      debug: var=device_output.stdout_lines
