---
# Main playbook for lab-config

- name: Set default lab config and any IP connectivity
  hosts: "{{ hosts }}"

  connection: local
  gather_facts: no
  vars_files:
    - topology.yml

  roles:
    - clean-files
    - common
    - { role: inet-topology, when: router == "yes" }

# add additional roles above to build complete configurations

  tasks:
    - name: check if the snippets directory exists before we try to assemble
      local_action: stat path=configs/snippets/{{ inventory_hostname }}
      register: snippets
      tags: always

    - name: Assemble snippets into one config file for uploading to device from the devices -snippets- directory
      assemble: src=configs/snippets/{{ inventory_hostname }} dest=configs/{{ inventory_hostname }}.conf
      when: snippets.stat.exists == True
      tags: always
