---
# Upgrade Junos device
# To run this playbook you need to specify "-e hosts=<host, group name or 'all'>"
- name: Upgrade devices
  hosts: "{{ hosts }}"
  vars_files:
    - creds.yml
  connection: local
  gather_facts: no
  roles:
    - upgrade-device
