---
# handlers file for upload-configs

  - name: remove-device-config
    file: path=configs/{{ inventory_hostname }}.conf state=absent
    tags: remove-configs
    notify: remove-device-snippets

  - name: remove-device-snippets
    file: path=configs/snippets/{{ inventory_hostname }} state=absent
    tags: remove-configs
