---
# Builds config with a config for MX and QFX
  - name: Create config snippet directory for device
    file: path=configs/snippets/{{ inventory_hostname }} state=directory

  - name: Build default configs for devices and putting into -snippets- directory
    template: src=evpn-ibgp.j2 dest=configs/snippets/{{ inventory_hostname }}/evpn-ibgp.conf
