# mx80-7
management_interface_ip: 172.30.105.67/23
lo0_ip: 1.1.105.67

evpn_mh_interfaces:
  - name: ae0
    description: to qfx5100-r04-2 xe-0/0/0
    esi: 00:00:11:11:22:22:33:33:44:45
    mode: all-active
    ae_members:
      - ge-1/1/9
