host_name: mx80-8
management_interface_ip: 172.30.105.68/23
lo0_ip: 1.1.105.68

inet_interfaces:
#  - name: ge-1/1/1
#    ip_address: 1.0.0.22/31
#    description: to qfx5100-5
  - name: ge-1/1/2
    ip_address: 1.0.0.19/31
    description: to mx80-2

underlay_inet_interfaces:
#  - ge-1/1/1
  - ge-1/1/2
