host_name: mx80-4
management_interface_ip: 172.30.105.64/23
lo0_ip: 1.1.105.64

inet_interfaces:
#  - name: ge-1/1/3
#    ip_address: 1.0.0.0/31
#    description: to qfx5100-1
  - name: ge-1/1/2
    ip_address: 1.0.0.16/31
    description: to mx80-7
#  - name: ge-1/0/3
#    ip_address: 1.0.0.2/31
#    description: to qfx5100-2
  - name: ge-1/1/4
    ip_address: 8.8.8.0/31
    description: to mx80-6

underlay_inet_interfaces:
  - ge-1/1/2
#  - ge-1/1/3
  - ge-1/1/4
#  - ge-1/0/3

ae_interfaces:
  - name: ae0
    description: my interface
    esi: 00:00:11:11:22:22:33:33:44:44
    mode: all-active
    ae_members:
      - ge-0/0/0
      - ge-0/0/1
  - name: ae1
    description: your interface
    esi: 00:00:11:11:22:22:33:33:44:45
    mode: all-active
    ae_members:
      - ge-0/0/2
      - ge-0/0/3
