# qfx5100-1
management_interface_ip: 172.30.105.41/23
lo0_ip: 1.1.105.41

lags:
  - name: ae0
    description: to mx80-7 and 8
    members:
      - xe-0/0/0
      - xe-0/0/1

vlans:
  - name: servers
    id: 100
    irb: 172.16.0.10/24
    trunk_ifs:
      - ae0
      - xe-0/0/10
  - name: other
    id: 200
    irb: 110.0.0.10/24
    trunk_ifs:
      - ae0
      - xe-0/0/10
